app/models.py
#Models.py file
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from . import login_manager
from flask_login import UserMixin, LoginManager
from datetime import datetime
from flask_login import UserMixin



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    '''
    class for users
    '''
    __tablename__='users'
    id = db.Column(db.Integer,primary_key=True)
    profile_image = db.Column(db.String, nullable = False, default = 'default_profile_image.png')
    email = db.Column(db.String(100), unique = True, index =True)
    username = db.Column(db.String(72), unique=True,index=True)
    password_hash = db.Column(db.String(255))
    confirmed =db.Column(db.Boolean, default = False)

    # Relationship with the Blog Post
    posts = db.relationship('Blog', backref = 'author', lazy = "dynamic")
     # Relationship with the Comments 
    comments = db.relationship('Comment', backref='author', lazy='dynamic')

    def generate_confirmation_token(self,expiration=3600):
        """
        We would like to send out a confirmation email to make sure the 
        email account provided is legit and that the user can again confirm
        their registration.
        """
        return s.dumps({'confirm':self.id}).decode('utf-8')


    



    def __init__(self,email, username, password):
        self.email = email
        self.username =  username
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)
        
    def __repr__(self):
        return f"User {self.username}"

    
class Blog(db.Model):
    __tablename__ = "blogs"
    '''
    Class for blog posts
    '''
    # Relationship with the user table
    users = db.relationship(User)

    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'), nullable = False)
    timestamp = db.Column(db.DateTime, index=True, nullable = False, default=datetime.utcnow)
    title = db.Column(db.String(120), nullable=False)
    body = db.Column(db.Text, nullable = False)

    # Relationship with the Comments 
    comments = db.relationship('Comment', backref='blogs', lazy='dynamic')
    
    def __init__(self,title, body, user_id):
        self.title = title
        self.body = body
        self.user_id = user_id
        
    def __repr__(self):
        return f"POST ID:{self.id} -- Date: {self.timestamp}"    

class Comment(db.Model):
    __tablename__='comments'
    # users = db.relationship(User)
    # blog = db.relationship(Blog)

    id  = db.Column(db.Integer, primary_key = True)
    body = db.Column(db.String)
    timestamp = db.Column(db.DateTime, default = datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    blog_id = db.Column(db.Integer, db.ForeignKey("blogs.id"))
    

class Quote:
    def __init__(self,id, author, quote, permalink):
        self.id = id
        self.author = author 
        self.quote  = quote
        self.permalink =  permalink

app/blogs/forms.py
# blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    body = TextAreaField('Text',validators=[DataRequired()])
    submit = SubmitField("Submit")


class CommentForm(FlaskForm):
    body = TextAreaField('Text',validators=[DataRequired()])
    submit = SubmitField("Submit")





app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_moment import Moment

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.strong'


bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
    
    app = Flask(__name__)
    moment = Moment(app)
    
    #Creating app configurations
    
    app.config.from_object(config_options[config_name])
    
    
    #Initialing bootstrap
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    #Registering Blueprints
    from app.auth import auth as auth_blueprint
    from app.main import main as main_blueprint
    from app.blogs import blogs as blogs_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint,url_prefix='/auth')
    app.register_blueprint(blogs_blueprint, url_prefix = '/')

    app.config['SECRET_KEY'] = '098&8&u^secreHHstring'
    
    
    return app
    
    

app/blogs/__init__.py
from flask import Blueprint
blogs = Blueprint('blogs',__name__)
from . import views

app/blogs/views.py
from flask import render_template, url_for, request, redirect, flash
from flask_login import current_user, login_required
from app import db
from app.models import Blog, User, Comment
from app.blogs.forms import PostForm, CommentForm
from app.blogs import blogs



# CREATE A BLOG

@blogs.route('/create', methods = ['GET', 'POST'])
@login_required
def create_post():
    post_form = PostForm()
    if post_form.validate_on_submit():
        post = Blog(title = post_form.title.data,
                    body = post_form.body.data,
                    user_id = current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post saved')
        return redirect(url_for('main.index'))
    return render_template('blog/create_post.html', post_form=post_form)


# VIEW A POST
@blogs.route('blog/<int:post_id>')
def post(post_id):
    post = Blog.query.get_or_404(post_id)
    return render_template('blog/post.html', title =post.title, date = post.timestamp, post = post)



@blogs.route('blog/<int:post_id>/update', methods = ['GET', 'POST'])
@login_required
def update(post_id):
    '''
    function to update post
    '''
    post = Blog.query.get_or_404(post_id)
    if post.author!=current_user:
        #403 error is forbidden
        abort(403)
    post_form  = PostForm()

    if post_form.validate_on_submit():
        post.title = post_form.title.data
        post.body = post_form.body.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('blogs.post', post_id=post.id))

    elif request.method == 'GET':
        post_form.title.data = post.title
        post_form.body.data = post.body

    return render_template('blog/create_post.html',title = 'Updating', post_form = post_form)


@blogs.route('blog/<int:post_id>/delete', methods = ['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Blog.query.get_or_404(post_id)
    if post.author!=current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()

    flash('Post deleted.')
    return redirect(url_for('main.index'))



@blogs.route('/blog/<int:id>/comment', methods = ['GET','POST'])
@login_required
def comment(id):
    post = Blog.query.get_or_404(id)
    form_comment = CommentForm()

    if form_comment.validate_on_submit():
        comment = Comment(body = form_comment.body.data,
                            blog_id = post.id,
                          author_id= current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comments added successfuly!')
        return redirect(url_for('.post', id=post.id))

    from pprint import pprint
    pprint(post)
    return render_template('blog/post.html',post =post, form_comment=form_comment)
    

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
#main/views.py

from flask import render_template, request, redirect, Blueprint
from app.main import main
from app.auth import auth
from app.request import get_quote
from app.models import Blog

@main.route('/')
def index():
    '''
    Homepage 

    '''

    quotes = get_quote()

    page = request.args.get('page', 1, type=int)
    posts = Blog.query.order_by(Blog.timestamp.desc()).all()
    return render_template('index.html',quotes = quotes, posts=posts)



@main.route('/info')
def info():
    '''
    Infor page
    '''
    return render_template('info.html')



# Comments.

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template("profile/profile.html", user = user, posts = posts)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bloggy Blogs</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
</body>
    {% extends 'bootstrap/base.html' %}
    {% block navbar%}
    {% include 'navbar.html' %}
    {% endblock %}
    
    
    {% block content %}
    
    {% endblock %}

    {% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/blog/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container"> 
        <div class="row">
          <div class= "col-md-2"> </div>
          <div class="col-md-8">
          <!-- Create Post form -->
          {{wtf.quick_form(form_comment)}}
         </div>
         <div clas="col-md-2"> </div>
        </div>
    </div>
    

{% endblock %}

app/templates/blog/create_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container"> 
        <div class="row">
          <div class= "col-md-2"> </div>
          <div class="col-md-8">
          <!-- Create Post form -->
          {{wtf.quick_form(post_form)}}
         </div>
         <div clas="col-md-2"> </div>
        </div>
    </div>
    

{% endblock %}

app/templates/blog/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}



{% block content %}
<div class="container">
    <h2>{{title}}</h2>
    
    <h4>Date published: {{post.timestamp.strftime('%B %d, %Y')}}</h4>
    <p>
        {{post.body}}

    </p>
    <div>
      <a href="{{ url_for('.post', post_id=post.id) }}">Comment
      
          

          <span class="label label-primary">
              {{ post.comments.count() }} Comments
          </span>
      
      </a>

    </div>

    {% if post.author == current_user %}
    <div>

        <a href="{{url_for('blogs.update', post_id = post.id)}}">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_post">Delete</button>
    </div>

    {% endif %}

</div>
<div class="modal" tabindex="-1" role="dialog" id="delete_post">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Post?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Confirm if you want to the delete post!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <form action="{{url_for('blogs.delete_post', post_id = post.id)}}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>



{% endblock  %}

app/templates/fourOwfour.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 HTML Tempalte by Colorlib</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="static/css/style.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
			</div>
			<h2>404 - Page not found</h2>
			<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p>
			<a href="{{url_for('main.index')}}">Go To Homepage</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
        <h1 class="display-4">Bloggy Blogs</h1>
        <p class="lead">This is a personal blogging website where you can create and share your opinions and other users can read and comment on them. Additionally, there is a feature that displays random quotes to inspire users. </p>
        <hr class="my-4">
        <p>Come share our great posts. Add yours to the mix as well.</p>
        <a class="btn btn-primary btn-sm" href="{{ url_for('main.info')}}" role="button">Learn more about this page</a>
      </div>



    <div class="container">
      <h3>Random Quotes</h3>

     
      <article class="row">
          {% for quote in quotes %}
          <blockquote class="ten columns centered">
            <p>{{quote.quote}}</p>
            <footer class="cite">
              &mdash; {{quote.author}}
            </footer>
          </blockquote>
          <footer>
            <br>
            <p>
            <a href="{{quote.permalink}}" target="_blank">Quote home</a>
            </p>
            <br>
          </footer>
        </article>
      {% endfor %}
    </div>
    <div class="container">
      <h2>Blogs Page</h2>
      {% for post in posts %}
      <div class="card">
        <div class="card-body">
          <h3> <a class="card-title">{{post.title}}</a></h3>
            <p>Posted by :{{post.author.username}}</p><br>
          <p>Published: {{ moment(post.timestamp).fromNow() }} </p>
          <a class="btn btn-primary" href="{{url_for('blogs.post', post_id = post.id)}}">Read Post</a>
          
          </div>

      </div>

      {% endfor %}

    </div>


{% endblock %}

app/templates/info.html
{% extends "base.html" %}


{% block content %}
  <div class="jumbotron">
    <h1>Information about us</h1>
<p>
  Welcome to blogs page. We provide a random quote every time the page refreshes. At the same time, we let users register and post their own quotes.
</p>
  </div>
{% endblock %}

app/templates/navbar.html
<div>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <a class="nav-link"><a href="{{ url_for('main.index')}}">Home</a>
        <a class="nav-link"><a href="{{ url_for('main.info')}}">About Us</a>
        {% if current_user.is_authenticated %}
        
        <a class="nav-link"><a href="{{url_for('auth.account')}}">Account</a>
        <a class="nav-link"><a href="{{url_for('blogs.create_post')}}">Create Post</a>
        <a class="nav-link"><a href="{{url_for('auth.logout')}}">Log Out</a>

        {% else %}
        <a class="nav-link"><a href="{{url_for('auth.login')}}">Log In</a>
        <a class="nav-link"><a href="{{url_for('auth.register')}}">Register</a>
        {% endif %}
          <form class="form-inline my-2 my-lg-0 navbar-right" >
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
      </nav>
    </div>

app/templates/user_post.html
{% extends "base.html" %}

{% block content %}

<div class="container">
	<div class = "jumbotron">
		<div align= 'center'>
			<h1>Welcome to the page for {{current_user.username}}</h1>

		</div>
	</div>

{% for post in posts %}

<h2><a href="{{url_for('blog_posts.blog_post', blog_post_id = post.id)}}">{{post.title}}</a></h2>
Post Author: <a href="{{url_for('users.user_post', username = post.author.username)}}">{{post.author.username}}</a>

<p class = 'text-muted'>Published on : {{post.timestamp.strftime("%Y-%m-%d")}}</p>
<br>
<p>{{post.body}}</p>
<br>
{% endfor %}
</div>


{% endblock %}